/**
 * The monthly digest — the pure model (ARCHITECTURE.md).
 *
 * **A second lens, not a fourth period.** `src/lib/reports.ts` answers "how was
 * the last N days"; this answers "what did last month cost, and what should I
 * expect next". They cannot be the same model: every field on `SpendingReport`
 * is coherent because all its windows are the same length, and calendar months
 * are 28–31 days.
 *
 * Same discipline as `reports.ts` all the same — everything here is a pure
 * function of `(receipts, disbursements, subscriptions, month, today)`, which is
 * what lets `/reports/monthly` and the email agree about every number by
 * construction. `monthly-digest-runner.ts` does the I/O.
 *
 * The shared primitives are imported rather than re-derived: `isExcludedCategory`
 * so both lenses agree on what Rent is, `nameGroupKey` so store and entity
 * grouping matches `/stores`, `computeSavings` so a discount is worth the same
 * everywhere.
 */

import {
  BIG_SPENDER,
  DIGEST_BASELINE_MONTHS,
  DIGEST_MAX_GRID_CATEGORIES,
  DIGEST_QUIET_WIN_THRESHOLD,
  DIGEST_TOP_STORES,
  EATING_OUT_SOCIAL,
  EATING_OUT_STRESSED,
  FORECAST_HORIZON_MONTHS,
  FORECAST_MIN_TRIM_MONTHS,
  FORECAST_TREND_THRESHOLD,
} from "@/lib/config";
import type {
  Disbursement,
  MergedReceipt,
  Subscription,
} from "@/lib/data/types";
import {
  addMonthsToKey,
  daysInMonth,
  monthEnd,
  monthKeyOf,
  monthStart,
  precedingMonths,
} from "@/lib/dates";
import {
  nameGroupKey,
  rankSpellings,
  type SpellingStat,
  tallySpelling,
} from "@/lib/name-groups";
import { isExcludedCategory } from "@/lib/reports";
import { computeSavings } from "@/lib/savings";
import { nthChargeDate } from "@/lib/subscriptions";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Which of the three rules put a receipt in the big-spenders table. */
export type BigSpenderReason = "floor" | "category-relative" | "share-of-month";

export interface BigSpenderRow {
  receiptId: number;
  date: string;
  store: string;
  category: string;
  /** Net — `actual_price`, so refunds have already come off. */
  amount: number;
  /** Every rule it satisfied. Never empty. */
  reasons: BigSpenderReason[];
  /** The category's trailing median receipt. Null unless the relative rule fired. */
  categoryMedian: number | null;
  /** e.g. 3.4, for "3.4× typical Transportation". Null unless the relative rule fired. */
  multipleOfMedian: number | null;
  /** 0..1 of the month's all-in spend. */
  shareOfAllIn: number;
  /** False for Travel/School/Rent — those sit outside the habitual figure. */
  inHabitual: boolean;
  /**
   * Generated by a subscription. Exempt from the relative and share rules, so a
   * recurring charge can only appear here by clearing the absolute floor — and
   * when it does, it is labelled, because it is the opposite of a one-off.
   */
  recurring: boolean;
}

export interface CategoryGridRow {
  category: string;
  /** Same order and length as `CategoryMonthGrid.months`. Null = month predates the ledger. */
  values: (number | null)[];
  /** Sum across the usable months. What the top-N ranking uses. */
  total: number;
}

export interface CategoryMonthGrid {
  /** Oldest first, ending with the digest's own month. */
  months: string[];
  rows: CategoryGridRow[];
  /** The tail beyond `DIGEST_MAX_GRID_CATEGORIES`, summed per month. Null when nothing was rolled up. */
  otherRow: CategoryGridRow | null;
  /** Column totals. Null where the month predates the ledger. */
  totals: (number | null)[];
}

/** Which estimator produced a figure — the digest states it rather than implying one. */
export type EstimatorRule = "trimmed-mean" | "median";

export type TrendDirection = "rising" | "falling";

export interface ProjectedCategory {
  category: string;
  /** Per-month point estimate, one-offs already removed. */
  perMonth: number;
  /** p25 / p75 across the usable baseline months. Equal to `perMonth` when only one month is usable. */
  low: number;
  high: number;
  rule: EstimatorRule;
  usableMonths: number;
  /** Set when the last-3-month median diverges from the prior-3 by more than the threshold. */
  trend: TrendDirection | null;
}

export interface ProjectionTotal {
  total: number;
  low: number;
  high: number;
}

export interface Projection {
  /**
   * The month the next-month figure covers, "YYYY-MM".
   *
   * The month *after* the digest's — so a July digest, mailed on 3 August,
   * projects August. That month is already three days old when it arrives, and
   * projecting it anyway is deliberate: the estimate is a whole-month figure,
   * and the month you are living in is the one you are budgeting.
   */
  nextMonth: string;
  /** Whole calendar months the horizon covers, starting at `nextMonth`. */
  horizonMonths: number;
  /** Last month of the horizon, "YYYY-MM". */
  horizonThrough: string;

  categories: ProjectedCategory[];

  /** Estimated from the ledger. */
  habitualPerMonth: ProjectionTotal;
  /**
   * **Computed, not estimated** — from each subscription's schedule via
   * `nthChargeDate`. Carries no spread because it carries no uncertainty.
   */
  subscriptionsNextMonth: number;
  subscriptionsHorizon: number;

  /** habitual + subscriptions. Excludes rent, school and travel by construction. */
  nextMonthTotal: ProjectionTotal;
  horizonTotal: ProjectionTotal;

  /**
   * Average monthly one-off spend in *habitual* categories over the baseline.
   *
   * Deliberately **outside** every total above: one-offs are unforecastable, but
   * "unforecastable" is not "won't happen", and a budget built without a buffer
   * is short every time a car repair lands. Excluded-category one-offs are not
   * counted — the projection already says it omits rent, school and travel, so
   * folding tuition in here would double-count the omission.
   */
  oneOffBuffer: number;
}

export interface NamedTotal {
  /** The most-used spelling in the group — same display rule as `/stores`. */
  name: string;
  total: number;
  count: number;
}

/**
 * A category's month-over-baseline change, split into the two things that can
 * cause it.
 *
 * `frequencyEffect + ticketEffect === deltaSpent` exactly. The interaction term
 * is split evenly between them (the symmetric decomposition) rather than being
 * dumped on whichever is computed second, which would make the attribution
 * depend on argument order.
 *
 * **One-offs are stripped from both sides.** They have their own table, and a
 * single brake job would otherwise read as a ruinous rise in average ticket.
 */
export interface CategoryChangeRow {
  category: string;
  /** This month, one-offs removed. */
  spent: number;
  receiptCount: number;
  /** What was removed, so this reconciles against the grid. */
  oneOffsRemoved: number;
  baselineSpent: number;
  /** Mean receipts per usable baseline month. Fractional on purpose. */
  baselineCount: number;
  avgTicket: number;
  baselineAvgTicket: number;
  deltaSpent: number;
  /** Portion of `deltaSpent` from going more or less often. */
  frequencyEffect: number;
  /** Portion from each visit costing more or less. */
  ticketEffect: number;
}

export interface QuietWinRow {
  category: string;
  spent: number;
  baseline: number;
  /** Negative — this is the amount it came in under. */
  delta: number;
}

export interface EatingOutSplit {
  stressed: number;
  social: number;
  /** stressed / (stressed + social). Null when both are zero. */
  stressedShare: number | null;
  /** The same ratio across the usable baseline months. Null when there is nothing to compare. */
  baselineStressedShare: number | null;
}

export interface MonthlyDigest {
  /** "YYYY-MM" — the completed month this covers. */
  month: string;
  /** Inclusive, plain dates. Always the whole month; there is no partial day to trim. */
  window: { start: string; end: string };
  /** Reported because month totals are not comparable without it. */
  days: number;
  /** The "today" this was built against, so the email is self-describing. */
  generatedFor: string;

  /** The headline. Negative means the month cost more than it brought in. */
  net: { received: number; allInSpent: number; net: number };

  habitual: { spent: number; receiptCount: number };
  /** Travel / School / Rent. Itemized inside `bigSpenders`, not in their own section. */
  excluded: { spent: number };

  savings: { month: number; yearToDate: number };

  bigSpenders: BigSpenderRow[];
  /** Split so the table can foot to two subtotals plus the all-in line. */
  bigSpenderTotals: { habitual: number; excluded: number };

  grid: CategoryMonthGrid;
  projection: Projection;

  /** Unlinked disbursements only — a refund already reduced the spend figure. */
  income: { total: number; count: number; entities: NamedTotal[] };

  /** Habitual spend only. All-in would rank the landlord first every month. */
  topStores: NamedTotal[];

  changes: CategoryChangeRow[];
  quietWins: QuietWinRow[];
  eatingOut: EatingOutSplit | null;
}

// ---------------------------------------------------------------------------
// Statistics
//
// Small and explicit rather than pulled from a library: every one of these is
// four lines, and the digest's credibility rests on being able to check its
// numbers by hand against a literal array.
// ---------------------------------------------------------------------------

function ascending(values: readonly number[]): number[] {
  return [...values].sort((a, b) => a - b);
}

/** Assumes non-empty. */
function median(values: readonly number[]): number {
  const s = ascending(values);
  const mid = Math.floor(s.length / 2);
  return s.length % 2 === 0 ? (s[mid - 1]! + s[mid]!) / 2 : s[mid]!;
}

function mean(values: readonly number[]): number {
  return values.reduce((sum, v) => sum + v, 0) / values.length;
}

/** Drop the highest and lowest month, average the rest. Assumes length ≥ 3. */
function trimmedMean(values: readonly number[]): number {
  return mean(ascending(values).slice(1, -1));
}

/**
 * Linear-interpolated percentile (the PERCENTILE.INC / R type-7 convention).
 *
 * Six points is a crude sample to take a quartile from, and the digest says so
 * by reporting `usableMonths` next to the range rather than presenting it as
 * precise.
 */
function percentile(values: readonly number[], p: number): number {
  const s = ascending(values);
  if (s.length === 1) return s[0]!;
  const idx = p * (s.length - 1);
  const lo = Math.floor(idx);
  const hi = Math.ceil(idx);
  if (lo === hi) return s[lo]!;
  return s[lo]! + (s[hi]! - s[lo]!) * (idx - lo);
}

/**
 * The forecast estimator, and the rule it used.
 *
 * Trimmed mean once there are enough months to trim, median below that. Never
 * a plain mean — one stock-up month must not set a budget — and never a fitted
 * trend, because on six noisy points the slope's standard error is large enough
 * that extrapolating it produces confident nonsense.
 */
function estimate(values: readonly number[]): {
  value: number;
  rule: EstimatorRule;
} {
  if (values.length >= FORECAST_MIN_TRIM_MONTHS) {
    return { value: trimmedMean(values), rule: "trimmed-mean" };
  }
  return { value: median(values), rule: "median" };
}

/**
 * Rising / falling when the recent half diverges from the older half.
 *
 * Exists because the trimmed mean is *deliberately* blind to drift: something
 * has to say when the stable number is about to be wrong. Needs the full
 * baseline — half a series can't have two halves.
 */
function trendOf(series: readonly number[]): TrendDirection | null {
  if (series.length < DIGEST_BASELINE_MONTHS) return null;
  const half = Math.floor(series.length / 2);
  const older = median(series.slice(0, half));
  const recent = median(series.slice(series.length - half));
  if (older <= 0) return null;
  const change = (recent - older) / older;
  if (Math.abs(change) < FORECAST_TREND_THRESHOLD) return null;
  return change > 0 ? "rising" : "falling";
}

function sumBy<T>(rows: readonly T[], value: (row: T) => number): number {
  return rows.reduce((sum, row) => sum + value(row), 0);
}

// ---------------------------------------------------------------------------
// Month slices
// ---------------------------------------------------------------------------

interface MonthSlice {
  month: string;
  /**
   * The ledger reaches back this far. A month that predates it has no data *for
   * a reason that has nothing to do with spending* — same trap `reports.ts`
   * avoids by dropping baselines rather than counting them as zero.
   */
  covered: boolean;
  habitual: MergedReceipt[];
  excluded: MergedReceipt[];
  habitualSpent: number;
  allInSpent: number;
  /**
   * Habitual spend and receipt count per category, folded in one pass.
   *
   * Precomputed for the reason `reports.ts` precomputes its baseline totals:
   * the grid, the forecast and the change decomposition each want every
   * category in every month, and re-filtering the month's rows once per
   * category turns one pass into `categories × months` of them.
   */
  categorySpent: Map<string, number>;
  categoryCount: Map<string, number>;
}

function sliceMonth(
  byMonth: Map<string, MergedReceipt[]>,
  month: string,
  covered: boolean,
): MonthSlice {
  const rows = byMonth.get(month) ?? [];
  const habitual: MergedReceipt[] = [];
  const excluded: MergedReceipt[] = [];
  const categorySpent = new Map<string, number>();
  const categoryCount = new Map<string, number>();

  for (const r of rows) {
    if (isExcludedCategory(r.category)) {
      excluded.push(r);
      continue;
    }
    habitual.push(r);
    categorySpent.set(
      r.category,
      (categorySpent.get(r.category) ?? 0) + r.actual_price,
    );
    categoryCount.set(r.category, (categoryCount.get(r.category) ?? 0) + 1);
  }

  const habitualSpent = sumBy(habitual, (r) => r.actual_price);
  return {
    month,
    covered,
    habitual,
    excluded,
    habitualSpent,
    allInSpent: habitualSpent + sumBy(excluded, (r) => r.actual_price),
    categorySpent,
    categoryCount,
  };
}

/**
 * Group rows by `nameGroupKey`, displaying the group's most-used spelling.
 *
 * Reuses the Stores/Entities display rule rather than picking, say, the first
 * spelling encountered: the digest and `/stores` must not disagree about what a
 * store is called.
 */
function groupByName<T>(
  rows: readonly T[],
  nameOf: (row: T) => string,
  dateOf: (row: T) => string,
  valueOf: (row: T) => number,
): NamedTotal[] {
  const groups = new Map<
    string,
    { spellings: Map<string, SpellingStat>; total: number; count: number }
  >();

  for (const row of rows) {
    const key = nameGroupKey(nameOf(row));
    let group = groups.get(key);
    if (!group) {
      group = { spellings: new Map(), total: 0, count: 0 };
      groups.set(key, group);
    }
    tallySpelling(group.spellings, nameOf(row), dateOf(row));
    group.total += valueOf(row);
    group.count += 1;
  }

  return [...groups.values()]
    .map((group) => ({
      name: rankSpellings(group.spellings.values())[0]?.spelling ?? "",
      total: group.total,
      count: group.count,
    }))
    .sort((a, b) => b.total - a.total || a.name.localeCompare(b.name));
}

// ---------------------------------------------------------------------------
// Big spenders
// ---------------------------------------------------------------------------

/**
 * Each category's typical receipt, over `BIG_SPENDER.medianMonths` ending with
 * the digest's month.
 *
 * **Median, not mean** — the mean is dragged upward by the very outlier the rule
 * exists to detect, so a category with one $600 repair would need a second $600
 * repair to flag. Subscription-generated charges are left out: many identical
 * small charges would drag the median down and make ordinary purchases look
 * exceptional.
 *
 * One map for every month evaluated, taken over the window ending at the digest
 * month rather than recomputed per month. That means a month six back is judged
 * against a median that includes later data — correct here, because this is a
 * baseline for a photograph, not a backtest of a live signal.
 */
function categoryMedians(
  receipts: readonly MergedReceipt[],
  month: string,
): Map<string, number> {
  const from = monthStart(addMonthsToKey(month, -(BIG_SPENDER.medianMonths - 1)));
  const to = monthEnd(month);

  const byCategory = new Map<string, number[]>();
  for (const r of receipts) {
    if (r.date < from || r.date > to) continue;
    if (r.subscription_id != null) continue;
    if (r.actual_price <= 0) continue; // a fully refunded receipt is not a purchase
    const list = byCategory.get(r.category);
    if (list) list.push(r.actual_price);
    else byCategory.set(r.category, [r.actual_price]);
  }

  const out = new Map<string, number>();
  for (const [category, prices] of byCategory) {
    out.set(category, median(prices));
  }
  return out;
}

/**
 * The three rules, unioned (ARCHITECTURE.md).
 *
 * `relativeFloor` guards *both* the relative and the share rule. Without it the
 * share rule turns a $5 receipt into a "big spender" in a $100 month, which is
 * technically 5% and obviously absurd.
 */
function qualifyBigSpender(
  receipt: MergedReceipt,
  medians: Map<string, number>,
  allInSpent: number,
): { reasons: BigSpenderReason[]; categoryMedian: number | null } {
  const reasons: BigSpenderReason[] = [];
  const amount = receipt.actual_price;
  const recurring = receipt.subscription_id != null;

  if (amount >= BIG_SPENDER.absoluteFloor) reasons.push("floor");

  const categoryMedian = medians.get(receipt.category) ?? null;
  const relativeApplies = !recurring && amount >= BIG_SPENDER.relativeFloor;

  if (
    relativeApplies &&
    categoryMedian !== null &&
    categoryMedian > 0 &&
    amount >= categoryMedian * BIG_SPENDER.relativeMultiple
  ) {
    reasons.push("category-relative");
  }

  if (
    relativeApplies &&
    allInSpent > 0 &&
    amount >= allInSpent * BIG_SPENDER.shareOfAllIn
  ) {
    reasons.push("share-of-month");
  }

  return {
    reasons,
    categoryMedian: reasons.includes("category-relative") ? categoryMedian : null,
  };
}

function bigSpendersIn(
  slice: MonthSlice,
  medians: Map<string, number>,
): BigSpenderRow[] {
  const rows: BigSpenderRow[] = [];
  for (const receipt of [...slice.habitual, ...slice.excluded]) {
    const { reasons, categoryMedian } = qualifyBigSpender(
      receipt,
      medians,
      slice.allInSpent,
    );
    if (reasons.length === 0) continue;
    rows.push({
      receiptId: receipt.id,
      date: receipt.date,
      store: receipt.store,
      category: receipt.category,
      amount: receipt.actual_price,
      reasons,
      categoryMedian,
      multipleOfMedian:
        categoryMedian !== null && categoryMedian > 0
          ? receipt.actual_price / categoryMedian
          : null,
      shareOfAllIn:
        slice.allInSpent > 0 ? receipt.actual_price / slice.allInSpent : 0,
      inHabitual: !isExcludedCategory(receipt.category),
      recurring: receipt.subscription_id != null,
    });
  }
  return rows.sort((a, b) => b.amount - a.amount || a.date.localeCompare(b.date));
}

// ---------------------------------------------------------------------------
// Subscriptions — computed, not estimated
// ---------------------------------------------------------------------------

/**
 * Total subscription charges falling in `[from, to]`.
 *
 * Walks each schedule forward from `charges_generated`, which is where the next
 * unwritten charge starts. Charge dates increase monotonically, so the loop
 * exits on the first one past the window; the iteration cap is a backstop
 * against a mistyped daily interval, not a real bound.
 *
 * Paused subscriptions are skipped — an inactive schedule owes nothing.
 */
function projectedSubscriptionSpend(
  subscriptions: readonly Subscription[],
  from: string,
  to: string,
): number {
  const MAX_STEPS = 2000;
  let total = 0;

  for (const sub of subscriptions) {
    if (!sub.active) continue;
    for (let step = 0; step < MAX_STEPS; step += 1) {
      const date = nthChargeDate(
        sub.start_date,
        sub.interval_unit,
        sub.interval_count,
        sub.charges_generated + step,
      );
      if (date > to) break;
      if (date >= from) total += sub.price;
    }
  }

  return total;
}

// ---------------------------------------------------------------------------
// The builder
// ---------------------------------------------------------------------------

export function buildMonthlyDigest(
  receipts: MergedReceipt[],
  disbursements: Disbursement[],
  subscriptions: Subscription[],
  month: string,
  today: string,
): MonthlyDigest {
  const start = monthStart(month);
  const end = monthEnd(month);

  // The ledger's own start, for the same reason `reports.ts` computes it: a
  // month before the first receipt is unknown, not empty.
  const ledgerStart = receipts.reduce<string | null>(
    (min, r) => (min === null || r.date < min ? r.date : min),
    null,
  );
  // `monthStart`, not `monthEnd`: the ledger must cover the WHOLE month. A month
  // the ledger only half-covers is a partial month reported as a complete one,
  // which reads as a lean month and biases every baseline built from it — the
  // same trap `reports.ts` avoids by dropping baselines rather than zeroing them.
  const covers = (key: string) =>
    ledgerStart !== null && ledgerStart <= monthStart(key);

  const byMonth = new Map<string, MergedReceipt[]>();
  for (const r of receipts) {
    const key = monthKeyOf(r.date);
    const list = byMonth.get(key);
    if (list) list.push(r);
    else byMonth.set(key, [r]);
  }

  const baselineKeys = precedingMonths(month, DIGEST_BASELINE_MONTHS);
  const gridKeys = [...baselineKeys, month];

  const slices = new Map<string, MonthSlice>(
    gridKeys.map((key) => [key, sliceMonth(byMonth, key, covers(key))]),
  );
  const current = slices.get(month)!;
  const usableBaselines = baselineKeys
    .map((key) => slices.get(key)!)
    .filter((slice) => slice.covered);

  const medians = categoryMedians(receipts, month);

  // ---- big spenders --------------------------------------------------------

  const bigSpenders = bigSpendersIn(current, medians);

  // Per-month one-off sets, so the forecast baseline can be stripped by the
  // same rules that built the table above. Habitual categories only — the
  // excluded ones are outside the projection entirely.
  const oneOffsByMonth = new Map<string, Map<string, number>>();
  for (const slice of usableBaselines) {
    const perCategory = new Map<string, number>();
    for (const row of bigSpendersIn(slice, medians)) {
      if (!row.inHabitual || row.recurring) continue;
      perCategory.set(
        row.category,
        (perCategory.get(row.category) ?? 0) + row.amount,
      );
    }
    oneOffsByMonth.set(slice.month, perCategory);
  }

  const currentOneOffs = new Map<string, number>();
  for (const row of bigSpenders) {
    if (!row.inHabitual || row.recurring) continue;
    currentOneOffs.set(
      row.category,
      (currentOneOffs.get(row.category) ?? 0) + row.amount,
    );
  }

  /** A month's habitual spend in one category, with that month's one-offs removed. */
  const habitualExOneOffs = (slice: MonthSlice, category: string): number => {
    const gross = slice.categorySpent.get(category) ?? 0;
    const oneOff =
      slice.month === month
        ? (currentOneOffs.get(category) ?? 0)
        : (oneOffsByMonth.get(slice.month)?.get(category) ?? 0);
    return gross - oneOff;
  };

  // ---- grid ----------------------------------------------------------------

  const gridCategories = new Set<string>();
  for (const key of gridKeys) {
    const slice = slices.get(key)!;
    if (!slice.covered) continue;
    for (const category of slice.categorySpent.keys()) {
      gridCategories.add(category);
    }
  }

  const allGridRows: CategoryGridRow[] = [...gridCategories]
    .map((category) => {
      const values = gridKeys.map((key) => {
        const slice = slices.get(key)!;
        if (!slice.covered) return null;
        return slice.categorySpent.get(category) ?? 0;
      });
      return {
        category,
        values,
        // Ranked on the whole window, not on this month, so a row can't pop in
        // and out of the grid month to month and break the comparison.
        total: sumBy(values, (v) => v ?? 0),
      };
    })
    .sort((a, b) => b.total - a.total || a.category.localeCompare(b.category));

  const gridRows = allGridRows.slice(0, DIGEST_MAX_GRID_CATEGORIES);
  const gridTail = allGridRows.slice(DIGEST_MAX_GRID_CATEGORIES);

  const grid: CategoryMonthGrid = {
    months: gridKeys,
    rows: gridRows,
    otherRow:
      gridTail.length > 0
        ? {
            category: `${gridTail.length} other categories`,
            values: gridKeys.map((key, i) =>
              slices.get(key)!.covered
                ? sumBy(gridTail, (row) => row.values[i] ?? 0)
                : null,
            ),
            total: sumBy(gridTail, (row) => row.total),
          }
        : null,
    totals: gridKeys.map((key) => {
      const slice = slices.get(key)!;
      return slice.covered ? slice.habitualSpent : null;
    }),
  };

  // ---- projection ----------------------------------------------------------

  // Guarded rather than filtered afterwards: `median([])` and `percentile([])`
  // are NaN, and a NaN that gets filtered out later still had to exist first.
  // On a first-ever digest there are no usable baselines and nothing to project.
  const projectionCategories: ProjectedCategory[] =
    usableBaselines.length === 0
      ? []
      : [...gridCategories]
          .map((category) => {
            const series = usableBaselines.map((slice) =>
              habitualExOneOffs(slice, category),
            );
            const { value, rule } = estimate(series);
            return {
              category,
              perMonth: value,
              low: percentile(series, 0.25),
              high: percentile(series, 0.75),
              rule,
              usableMonths: series.length,
              trend: trendOf(series),
            } satisfies ProjectedCategory;
          })
          .sort(
            (a, b) =>
              b.perMonth - a.perMonth || a.category.localeCompare(b.category),
          );

  // The total is estimated from the total series, NOT by summing the category
  // estimates' ranges. Categories move together — a lean month is lean across
  // the board — so combining their spreads would assume an independence the
  // data does not have. The joint series already carries the real covariance.
  const totalSeries = usableBaselines.map((slice) =>
    sumBy([...gridCategories], (category) => habitualExOneOffs(slice, category)),
  );
  const habitualEstimate =
    totalSeries.length > 0
      ? estimate(totalSeries)
      : { value: 0, rule: "median" as EstimatorRule };
  const habitualPerMonth: ProjectionTotal = {
    total: habitualEstimate.value,
    low: totalSeries.length > 0 ? percentile(totalSeries, 0.25) : 0,
    high: totalSeries.length > 0 ? percentile(totalSeries, 0.75) : 0,
  };

  const nextMonth = addMonthsToKey(month, 1);
  const horizonThrough = addMonthsToKey(nextMonth, FORECAST_HORIZON_MONTHS - 1);

  const subscriptionsNextMonth = projectedSubscriptionSpend(
    subscriptions,
    monthStart(nextMonth),
    monthEnd(nextMonth),
  );
  const subscriptionsHorizon = projectedSubscriptionSpend(
    subscriptions,
    monthStart(nextMonth),
    monthEnd(horizonThrough),
  );

  // √n, not n. Monthly deviations are close to independent, so they partly
  // cancel over a multi-month total: scaling the half-widths linearly would
  // overstate the four-month spread by roughly 2×. The subscription figure is
  // known, so it shifts all three numbers by the same amount and widens nothing.
  const spread = Math.sqrt(FORECAST_HORIZON_MONTHS);
  const lowHalf = habitualPerMonth.total - habitualPerMonth.low;
  const highHalf = habitualPerMonth.high - habitualPerMonth.total;
  const horizonHabitual = habitualPerMonth.total * FORECAST_HORIZON_MONTHS;

  const projection: Projection = {
    nextMonth,
    horizonMonths: FORECAST_HORIZON_MONTHS,
    horizonThrough,
    categories: projectionCategories,
    habitualPerMonth,
    subscriptionsNextMonth,
    subscriptionsHorizon,
    nextMonthTotal: {
      total: habitualPerMonth.total + subscriptionsNextMonth,
      low: habitualPerMonth.low + subscriptionsNextMonth,
      high: habitualPerMonth.high + subscriptionsNextMonth,
    },
    horizonTotal: {
      total: horizonHabitual + subscriptionsHorizon,
      low: horizonHabitual - spread * lowHalf + subscriptionsHorizon,
      high: horizonHabitual + spread * highHalf + subscriptionsHorizon,
    },
    oneOffBuffer:
      usableBaselines.length > 0
        ? mean(
            usableBaselines.map((slice) =>
              sumBy(
                [...(oneOffsByMonth.get(slice.month)?.values() ?? [])],
                (v) => v,
              ),
            ),
          )
        : 0,
  };

  // ---- income --------------------------------------------------------------

  // Unlinked only: a linked disbursement is a refund, and a refund already came
  // off `actual_price`. Counting it here would report the same dollar twice.
  const unlinked = disbursements.filter(
    (d) =>
      d.refunded_from_receipt == null &&
      d.date_received >= start &&
      d.date_received <= end,
  );

  // ---- changes, quiet wins -------------------------------------------------

  const changes: CategoryChangeRow[] = [];
  const quietWins: QuietWinRow[] = [];

  for (const category of gridCategories) {
    const series = usableBaselines.map((slice) =>
      habitualExOneOffs(slice, category),
    );
    if (series.length === 0) continue;

    const baselineSpent = estimate(series).value;
    const oneOffsRemoved = currentOneOffs.get(category) ?? 0;
    const spent = habitualExOneOffs(current, category);

    if (baselineSpent > 0) {
      const drop = (baselineSpent - spent) / baselineSpent;
      if (drop >= DIGEST_QUIET_WIN_THRESHOLD) {
        quietWins.push({
          category,
          spent,
          baseline: baselineSpent,
          delta: spent - baselineSpent,
        });
      }
    }

    const receiptCount = current.categoryCount.get(category) ?? 0;
    const baselineCount = mean(
      usableBaselines.map((slice) => slice.categoryCount.get(category) ?? 0),
    );
    // No visits on one side means there is no average ticket to compare, and a
    // decomposition of "went from nothing to something" is just the total.
    if (receiptCount === 0 || baselineCount === 0) continue;

    const avgTicket = spent / receiptCount;
    // Derived from the estimated spend rather than averaged separately, so
    // baselineCount × baselineAvgTicket === baselineSpent exactly and the two
    // effects sum to the delta with no residual.
    const baselineAvgTicket = baselineSpent / baselineCount;

    changes.push({
      category,
      spent,
      receiptCount,
      oneOffsRemoved,
      baselineSpent,
      baselineCount,
      avgTicket,
      baselineAvgTicket,
      deltaSpent: spent - baselineSpent,
      frequencyEffect:
        (receiptCount - baselineCount) * ((baselineAvgTicket + avgTicket) / 2),
      ticketEffect:
        (avgTicket - baselineAvgTicket) * ((baselineCount + receiptCount) / 2),
    });
  }

  changes.sort((a, b) => Math.abs(b.deltaSpent) - Math.abs(a.deltaSpent));
  quietWins.sort((a, b) => a.delta - b.delta);

  // ---- eating out ----------------------------------------------------------

  const stressedKey = nameGroupKey(EATING_OUT_STRESSED);
  const socialKey = nameGroupKey(EATING_OUT_SOCIAL);
  const eatingOutTotal = (slice: MonthSlice, key: string) =>
    sumBy(
      slice.habitual.filter((r) => nameGroupKey(r.category) === key),
      (r) => r.actual_price,
    );

  const stressed = eatingOutTotal(current, stressedKey);
  const social = eatingOutTotal(current, socialKey);
  const baselineStressed = sumBy(usableBaselines, (s) =>
    eatingOutTotal(s, stressedKey),
  );
  const baselineSocial = sumBy(usableBaselines, (s) =>
    eatingOutTotal(s, socialKey),
  );

  const eatingOut: EatingOutSplit | null =
    stressed + social > 0 || baselineStressed + baselineSocial > 0
      ? {
          stressed,
          social,
          stressedShare:
            stressed + social > 0 ? stressed / (stressed + social) : null,
          baselineStressedShare:
            baselineStressed + baselineSocial > 0
              ? baselineStressed / (baselineStressed + baselineSocial)
              : null,
        }
      : null;

  // ---- savings -------------------------------------------------------------

  // Year to date runs to the END of the digest's month, not to `today`: the
  // digest mails on the 3rd, and a YTD figure that quietly included two days of
  // the following month would not reconcile against the month's own number.
  const yearStart = `${month.slice(0, 4)}-01-01`;
  const savingsYearToDate = sumBy(
    receipts.filter((r) => r.date >= yearStart && r.date <= end),
    computeSavings,
  );

  const receivedTotal = sumBy(unlinked, (d) => d.amount);
  const allInSpent = current.allInSpent;

  return {
    month,
    window: { start, end },
    days: daysInMonth(month),
    generatedFor: today,

    net: {
      received: receivedTotal,
      allInSpent,
      net: receivedTotal - allInSpent,
    },

    habitual: {
      spent: current.habitualSpent,
      receiptCount: current.habitual.length,
    },
    excluded: { spent: sumBy(current.excluded, (r) => r.actual_price) },

    savings: {
      month: sumBy([...current.habitual, ...current.excluded], computeSavings),
      yearToDate: savingsYearToDate,
    },

    bigSpenders,
    bigSpenderTotals: {
      habitual: sumBy(
        bigSpenders.filter((r) => r.inHabitual),
        (r) => r.amount,
      ),
      excluded: sumBy(
        bigSpenders.filter((r) => !r.inHabitual),
        (r) => r.amount,
      ),
    },

    grid,
    projection,

    income: {
      total: receivedTotal,
      count: unlinked.length,
      entities: groupByName(
        unlinked,
        (d) => d.entity,
        (d) => d.date_received,
        (d) => d.amount,
      ),
    },

    topStores: groupByName(
      current.habitual,
      (r) => r.store,
      (r) => r.date,
      (r) => r.actual_price,
    ).slice(0, DIGEST_TOP_STORES),

    changes,
    quietWins,
    eatingOut,
  };
}

// ---------------------------------------------------------------------------
// Shared presentation helpers
//
// Here rather than in either renderer, for the same reason `reports.ts` holds
// its own: a number formatted two ways in two places is a bug waiting for
// someone to compare a screenshot against an inbox.
// ---------------------------------------------------------------------------

const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const MONTH_ABBR = [
  "Jan", "Feb", "Mar", "Apr", "May", "Jun",
  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec",
];

/**
 * "Jul" — the grid's column header. Pure string work, per `CLAUDE.md`'s date
 * rule, and falls back to the raw key rather than rendering "undefined".
 */
export function formatMonthAbbr(monthKey: string): string {
  return MONTH_ABBR[Number(monthKey.slice(5, 7)) - 1] ?? monthKey;
}

/** "July 2026". */
export function formatMonthLong(monthKey: string): string {
  const name = MONTH_NAMES[Number(monthKey.slice(5, 7)) - 1];
  return name ? `${name} ${monthKey.slice(0, 4)}` : monthKey;
}

/** "July 2026" — the digest's title and subject line. */
export function digestTitle(digest: MonthlyDigest): string {
  return formatMonthLong(digest.month);
}

/** "the 6 months to Jun 2026", or null when there is no usable baseline. */
export function baselineLabel(digest: MonthlyDigest): string | null {
  const months = digest.projection.categories[0]?.usableMonths ?? 0;
  if (months === 0) return null;
  const last = digest.grid.months[digest.grid.months.length - 2];
  if (months === 1) return `the month to ${last ? formatMonthAbbr(last) : ""}`.trim();
  return `the ${months} months to ${last ? formatMonthAbbr(last) : ""}`.trim();
}

/**
 * "3.4× typical Transportation" / "over the $150 floor" / "5% of the month".
 *
 * The reason is the whole point of the table — a bare threshold cannot explain
 * why a brake job belongs in the same list as rent.
 */
export function bigSpenderReasonLabel(row: BigSpenderRow): string {
  if (row.reasons.includes("category-relative") && row.multipleOfMedian !== null) {
    return `${row.multipleOfMedian.toFixed(1)}× typical ${row.category}`;
  }
  if (row.reasons.includes("floor")) {
    return `over the $${BIG_SPENDER.absoluteFloor} floor`;
  }
  return `${Math.round(row.shareOfAllIn * 100)}% of the month`;
}

/** "went 4 more times" / "each visit cost $12 more" — whichever effect dominates. */
export function changeDriverLabel(row: CategoryChangeRow): string {
  const frequency = Math.abs(row.frequencyEffect);
  const ticket = Math.abs(row.ticketEffect);
  const visits = row.receiptCount - row.baselineCount;

  if (frequency >= ticket) {
    const n = Math.abs(visits);
    const rounded = n < 1 ? n.toFixed(1) : Math.round(n).toString();
    return `${visits >= 0 ? "went" : "skipped"} ${rounded} ${
      Math.round(n) === 1 ? "visit" : "visits"
    }`;
  }

  const diff = Math.abs(row.avgTicket - row.baselineAvgTicket);
  return `each visit cost $${diff.toFixed(2)} ${
    row.avgTicket >= row.baselineAvgTicket ? "more" : "less"
  }`;
}
