"use client";

import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatCurrency } from "@/lib/format";
import {
  bigSpenderReasonLabel,
  formatCompact,
  type MonthlyDigest,
} from "@/lib/monthly-digest";
import { formatShortDate } from "@/lib/reports";

/**
 * The month's largest purchases (ARCHITECTURE.md).
 *
 * **This is also the excluded-categories section.** Rent, school and travel are
 * always big spenders, so itemising them anywhere else would print the same
 * dollars in two tables. The "outside habitual" badge is what keeps them
 * readable as sitting outside every average above.
 *
 * Each row states *why* it qualified rather than just clearing a threshold —
 * that is the whole reason the rule is a union of three tests. "3.4× typical
 * Transportation" explains a brake job in a way "over $150" cannot.
 */
export function DigestBigSpenders({ digest }: { digest: MonthlyDigest }) {
  const { bigSpenders, bigSpenderTotals } = digest;

  if (bigSpenders.length === 0) {
    return (
      <div className="rounded-lg border border-border bg-card p-6 text-sm text-muted-foreground">
        Nothing unusually large this month.
      </div>
    );
  }

  return (
    <div className="rounded-lg border border-border bg-card">
      <Table>
        <TableHeader>
          <TableRow>
            <TableHead className="pl-4">Purchase</TableHead>
            <TableHead className="w-full min-w-40">Why it&rsquo;s here</TableHead>
            <TableHead className="text-right">Date</TableHead>
            <TableHead className="pr-4 text-right">Amount</TableHead>
          </TableRow>
        </TableHeader>
        <TableBody>
          {bigSpenders.map((row) => (
            <TableRow key={row.receiptId}>
              <TableCell className="max-w-44 pl-4">
                <div className="truncate font-medium" title={row.store}>
                  {row.store}
                </div>
                <div
                  className="truncate text-xs text-muted-foreground"
                  title={row.category}
                >
                  {row.category}
                </div>
              </TableCell>

              <TableCell>
                <div className="flex flex-wrap items-center gap-1.5">
                  <span className="text-sm text-muted-foreground">
                    {bigSpenderReasonLabel(row)}
                  </span>
                  {!row.inHabitual && (
                    <Badge
                      variant="outline"
                      title="Held out of the habitual figure and every average"
                    >
                      outside habitual
                    </Badge>
                  )}
                  {row.recurring && (
                    <Badge
                      variant="outline"
                      title="Generated by a subscription — recurring, not a one-off, and never stripped from the forecast"
                    >
                      recurring
                    </Badge>
                  )}
                </div>
              </TableCell>

              <TableCell className="text-right text-sm whitespace-nowrap text-muted-foreground tabular-nums">
                {formatShortDate(row.date)}
              </TableCell>

              <TableCell className="pr-4 text-right font-medium tabular-nums">
                {formatCurrency(row.amount)}
              </TableCell>
            </TableRow>
          ))}

          <TableRow className="border-t border-border">
            <TableCell className="pl-4 text-muted-foreground" colSpan={3}>
              In habitual
            </TableCell>
            <TableCell className="pr-4 text-right tabular-nums text-muted-foreground">
              {formatCompact(bigSpenderTotals.habitual)}
            </TableCell>
          </TableRow>
          <TableRow>
            <TableCell className="pl-4 text-muted-foreground" colSpan={3}>
              Rent, school, travel
            </TableCell>
            <TableCell className="pr-4 text-right tabular-nums text-muted-foreground">
              {formatCompact(bigSpenderTotals.excluded)}
            </TableCell>
          </TableRow>
          <TableRow className="font-semibold">
            <TableCell className="pl-4" colSpan={3}>
              All-in for the month
            </TableCell>
            <TableCell className="pr-4 text-right tabular-nums">
              {formatCurrency(digest.net.allInSpent)}
            </TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </div>
  );
}
