"use client";

import { Badge } from "@/components/ui/badge";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { formatCurrency } from "@/lib/format";
import {
  bigSpenderReasonLabel,
  type MonthlyDigest,
} from "@/lib/monthly-digest";
import { formatShortDate } from "@/lib/reports";

/**
 * The month's largest purchases (ARCHITECTURE.md).
 *
 * **This is also the excluded-categories section.** Rent, school and travel are
 * always big spenders, so itemising them anywhere else would print the same
 * dollars in two tables. The "outside habitual" badge is what keeps them
 * readable as sitting outside every average above.
 *
 * Each row states *why* it qualified rather than just clearing a threshold —
 * that is the whole reason the rule is a union of three tests. "3.4× typical
 * Transportation" explains a brake job in a way "over $150" cannot.
 */
export function DigestBigSpenders({ digest }: { digest: MonthlyDigest }) {
  const { bigSpenders } = digest;

  if (bigSpenders.length === 0) {
    return (
      <div className="flex flex-col gap-2">
        <div className="rounded-lg border border-border bg-card p-6 text-sm text-muted-foreground">
          Nothing unusually large this month.
        </div>
        <OneOffNote digest={digest} />
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2">
      <div className="rounded-lg border border-border bg-card">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead className="pl-4">Purchase</TableHead>
              <TableHead className="w-full min-w-40">
                Why it&rsquo;s here
              </TableHead>
              <TableHead className="text-right">Date</TableHead>
              <TableHead className="pr-4 text-right">Amount</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {bigSpenders.map((row) => (
              <TableRow key={row.receiptId}>
                <TableCell className="max-w-44 pl-4">
                  <div className="truncate font-medium" title={row.store}>
                    {row.store}
                  </div>
                  <div
                    className="truncate text-xs text-muted-foreground"
                    title={row.category}
                  >
                    {row.category}
                  </div>
                </TableCell>

                <TableCell>
                  <div className="flex flex-wrap items-center gap-1.5">
                    <span className="text-sm text-muted-foreground">
                      {bigSpenderReasonLabel(row)}
                    </span>
                    {!row.inHabitual && (
                      <Badge
                        variant="outline"
                        title="Held out of the habitual figure and every average"
                      >
                        outside habitual
                      </Badge>
                    )}
                    {row.recurring && (
                      <Badge
                        variant="outline"
                        title="Generated by a subscription — recurring, not a one-off, and never stripped from the forecast"
                      >
                        recurring
                      </Badge>
                    )}
                  </div>
                </TableCell>

                <TableCell className="text-right text-sm whitespace-nowrap text-muted-foreground tabular-nums">
                  {formatShortDate(row.date)}
                </TableCell>

                <TableCell className="pr-4 text-right font-medium tabular-nums">
                  {formatCurrency(row.amount)}
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
      <OneOffNote digest={digest} />
    </div>
  );
}

/**
 * What the projection leaves out, explained where its evidence is.
 *
 * A one-off is exactly the rows above **without** an "outside habitual" or
 * "recurring" badge — so this sits under the table rather than under the
 * forecast it modifies, where the number would be an assertion with nothing to
 * check it against.
 */
function OneOffNote({ digest }: { digest: MonthlyDigest }) {
  const { oneOffs } = digest;
  if (oneOffs.months === 0) return null;

  return (
    <p className="text-xs text-muted-foreground">
      Purchases like these in habitual categories — not rent, school, travel or
      subscriptions — are left out of{" "}
      <span className="text-foreground">What to expect</span>, because a car
      repair can&rsquo;t be predicted, only budgeted for. Over the{" "}
      {oneOffs.months === 1 ? "month" : `${oneOffs.months} months`} before this
      one there were{" "}
      <span className="tabular-nums text-foreground">{oneOffs.count}</span> of
      them totalling{" "}
      <span className="tabular-nums text-foreground">
        {formatCurrency(oneOffs.total)}
      </span>{" "}
      — about{" "}
      <span className="font-medium tabular-nums text-foreground">
        {formatCurrency(oneOffs.perMonth)} a month
      </span>{" "}
      worth setting aside.
    </p>
  );
}
