-- ============================================================================
-- 003_subscriptions.sql — recurring charges that GENERATE receipts.
-- Safe to re-run. Run AFTER 002_mutable_rows.sql.
--
-- FEATURES.md §0: `receipts` is the ledger of facts. A subscription is a
-- SCHEDULE, not a spend record — nothing in the app's math ever reads this
-- table. That is why adding it required zero changes to any chart, filter,
-- total or page: the new spending simply appears as receipts, which everything
-- already understands.
--
-- It also means there is deliberately no price-history table. Every past charge
-- is already a receipt carrying the amount actually paid, and past receipts are
-- immutable facts. A subscription only ever needs to know its CURRENT price.
-- ============================================================================

create table if not exists finance_tracker.subscriptions (
    id                bigint generated by default as identity primary key,
    name              text    not null,                    -- "Netflix Standard"
    store             text    not null,                    -- goes onto the receipt
    category          text    not null,                    -- goes onto the receipt
    price             numeric not null check (price > 0),   -- CURRENT price only (D4)
    interval_unit     text    not null check (interval_unit in ('day','week','month','year')),
    interval_count    int     not null default 1 check (interval_count >= 1),
    start_date        date    not null,                    -- date of the FIRST charge
    charges_generated int     not null default 0 check (charges_generated >= 0),
    active            boolean not null default true,
    note              text,
    created_at        timestamptz not null default now(),
    updated_at        timestamptz not null default now()
);

alter table finance_tracker.receipts
    add column if not exists subscription_id bigint
    references finance_tracker.subscriptions (id);

-- THE idempotency guard. Makes a double-charge impossible at the database layer
-- rather than in application logic. The runner inserts the receipt and THEN
-- advances charges_generated; a crash between the two leaves the counter
-- behind, so the next run recomputes the same due date and this index rejects
-- the re-insert with 23505 — which the runner treats as
-- success-already-recorded. That one rule is what makes the whole design
-- self-repairing without transactions (FEATURES.md §6.4).
create unique index if not exists receipts_subscription_charge_uniq
    on finance_tracker.receipts (subscription_id, date)
    where subscription_id is not null;

create index if not exists receipts_subscription_id_idx
    on finance_tracker.receipts (subscription_id)
    where subscription_id is not null;

drop trigger if exists subscriptions_set_updated_at on finance_tracker.subscriptions;
create trigger subscriptions_set_updated_at
    before update on finance_tracker.subscriptions
    for each row execute function finance_tracker.set_updated_at();

-- A custom schema inherits NO default privileges (see finance_tracker_schema.sql
-- §4) — a new table without these lines is unreachable, secret key or not.
revoke all on finance_tracker.subscriptions from public, anon, authenticated;
grant select, insert, update, delete on finance_tracker.subscriptions to service_role;

-- Pattern A backstop: RLS on, zero policies. Under service_role the policies
-- would be dead code anyway; the point is that a stray future `grant` can't
-- silently publish this table.
alter table finance_tracker.subscriptions enable row level security;

-- ----------------------------------------------------------------------------
-- After running this, regenerate the TypeScript types and take the output
-- verbatim (keep the whole file, including the other apps' `public` tables):
--
--   npx supabase gen types typescript --project-id <ref> \
--       --schema public --schema finance_tracker
-- ----------------------------------------------------------------------------
