-- ============================================================================
-- finance_tracker: schema, privileges, and RLS.
--
-- HOW TO RUN
--   Supabase Dashboard -> SQL Editor -> New query -> paste -> Run.
--   Safe to re-run.
--
-- AFTERWARDS
--   Project Settings -> API -> Exposed schemas must include `finance_tracker`.
--   Only `public` is exposed by default, and PostgREST serves nothing from an
--   unexposed schema — every request 404s, secret key or not.
--
-- THE MODEL — auth.md Pattern A (server-only tables)
--   Nothing in the browser ever talks to Supabase. Every read and write goes
--   through a route handler -> src/lib/data/source.ts -> the SECRET-key client
--   in src/lib/supabase/service.ts. The secret key bypasses RLS
--   unconditionally, so per-user policies (`auth.uid() = user_id`) would never
--   be evaluated by anything this app does — they'd be dead code, and they'd
--   require a user_id column on every row for an app with exactly one user.
--
--   What actually protects this data, in order:
--     1. Privileges — `anon` and `authenticated` hold NO privileges on these
--        tables. A request bearing the public anon key gets 42501, full stop.
--     2. RLS on, zero policies — the backstop. Costs one line per table and
--        changes nothing for service_role, but means a stray `grant` (or a
--        table later moved to `public`, where Supabase attaches default
--        privileges automatically) doesn't silently publish your finances.
--     3. App layer — OWNER_USER_IDS (src/lib/auth.ts), enforced in middleware
--        and re-checked at the top of every route handler.
--
--   Note the consequence of choosing this pattern: gate 3 is the ONLY thing
--   distinguishing you from any other signed-in user, because by the time a
--   query reaches Postgres it is already service_role. A route handler that
--   forgets `requireOwnerForApi()` has no database backstop behind it. That is
--   the deliberate trade — simplicity and no user_id plumbing, in exchange for
--   authorization living entirely in app code.
-- ============================================================================


-- ---------------------------------------------------------------------------
-- 1. Schema and schema-level privileges
--
-- USAGE goes to anon/authenticated too, matching how Supabase configures
-- `public` and how its own "custom schemas" recipe reads. USAGE alone conveys
-- no data access — it only permits looking objects up — and PostgREST's schema
-- introspection expects it. We deliberately stop short of the table grants
-- that recipe hands out; those are in section 4, service_role only.
-- ---------------------------------------------------------------------------
create schema if not exists finance_tracker;

grant usage on schema finance_tracker to anon, authenticated, service_role;


-- ---------------------------------------------------------------------------
-- 2. Tables
--
-- No `user_id`: with Pattern A there is no session at the database layer to
-- scope rows against, and this app has exactly one real user. `created_at` is
-- the provenance that's actually useful. (If this ever becomes genuinely
-- multi-user, that's a column add plus real policies plus moving off the
-- secret key — not a tweak.)
--
-- `generated by default as identity`, NOT `generated always`: the one-time
-- backfill inserts explicit `id` values to preserve the SQLite ids that
-- `disbursements.refunded_from_receipt` points at. `generated always` rejects
-- those with `428C9: cannot insert a non-DEFAULT value into column "id"`, and
-- PostgREST cannot emit the `overriding system value` clause that would allow
-- it.
-- ---------------------------------------------------------------------------
create table if not exists finance_tracker.receipts (
    id                  bigint      generated by default as identity primary key,
    store               text        not null,
    category            text        not null,
    price               numeric     not null,
    discount            numeric     not null default 0,
    discount_percentage numeric     not null default 0,
    note                text,
    date                date        not null,
    created_at          timestamptz not null default now()
);

create table if not exists finance_tracker.disbursements (
    id                    bigint      generated by default as identity primary key,
    entity                text        not null,
    amount                numeric     not null,
    date_received         date        not null,
    reason                text,
    refunded_from_receipt bigint      references finance_tracker.receipts (id),
    created_at            timestamptz not null default now()
);

-- Idempotent fixup if the tables already exist from an earlier run.
alter table finance_tracker.receipts      alter column id set generated by default;
alter table finance_tracker.disbursements alter column id set generated by default;


-- ---------------------------------------------------------------------------
-- 3. Indexes
--
-- Both loaders order by date descending and read the whole table; the refund
-- index supports the join in src/lib/data/merge.ts and the FK check that runs
-- whenever a receipt is deleted.
-- ---------------------------------------------------------------------------
create index if not exists receipts_date_idx
    on finance_tracker.receipts (date desc);

create index if not exists disbursements_date_received_idx
    on finance_tracker.disbursements (date_received desc);

create index if not exists disbursements_refunded_from_receipt_idx
    on finance_tracker.disbursements (refunded_from_receipt)
    where refunded_from_receipt is not null;


-- ---------------------------------------------------------------------------
-- 4. Table privileges — service_role only
--
-- RLS and privileges are INDEPENDENT gates, and a query that fails this one
-- never reaches RLS. service_role bypasses RLS but NOT privileges: without the
-- grant below, every call fails `42501: permission denied for table receipts`.
--
-- The `revoke` runs first and is the load-bearing line: it's what guarantees
-- the public anon key can't read these tables even though the schema is
-- exposed to PostgREST.
-- ---------------------------------------------------------------------------
revoke all on all tables in schema finance_tracker from public, anon, authenticated;

grant select, insert on
    finance_tracker.receipts,
    finance_tracker.disbursements
    to service_role;

-- Identity columns don't require sequence privileges the way `serial` does,
-- but the backfill's follow-up `setval(...)` calls do.
grant usage, select, update on all sequences in schema finance_tracker to service_role;

-- Deliberately NO `alter default privileges` for this schema. Supabase's
-- custom-schema recipe sets them for anon/authenticated; doing that here would
-- mean a future table silently starts out readable with the public anon key.
-- New tables get an explicit grant or they get nothing.

-- Only select and insert: the app issues no UPDATE and no DELETE anywhere (see
-- src/lib/data/supabase-source.ts), so even a leaked secret key cannot rewrite
-- or destroy history through PostgREST. Section 6 has what to add if you build
-- edit/delete UI.


-- ---------------------------------------------------------------------------
-- 5. Row level security — enabled, zero policies
--
-- This is Pattern A's backstop, not its primary defence. service_role bypasses
-- RLS entirely, so this changes nothing for the app; what it buys is that if a
-- `grant` to anon/authenticated ever slips in, RLS-on-with-no-policies still
-- denies both roles everything.
--
-- DO NOT add policies here. A policy would be dead code under service_role,
-- and adding one is a strong signal someone has started querying these tables
-- with a user session — at which point the whole model needs revisiting, not
-- patching.
--
-- Not used: `force row level security`. It would apply to the table owner too,
-- including you in the SQL editor, which reads as "my data vanished".
-- ---------------------------------------------------------------------------
alter table finance_tracker.receipts      enable row level security;
alter table finance_tracker.disbursements enable row level security;

-- Drops the per-user policies from the earlier `migration.md` §6 SQL, if you
-- ever ran it. Under Pattern A they are dead code.
drop policy if exists "owner full access" on finance_tracker.receipts;
drop policy if exists "owner full access" on finance_tracker.disbursements;


-- ---------------------------------------------------------------------------
-- 6. Verification, and later changes
--
-- Confirm the lockout is real. With the PUBLIC anon key, from anywhere:
--
--   curl "https://<ref>.supabase.co/rest/v1/receipts?select=id" \
--     -H "apikey: <anon key>" -H "Accept-Profile: finance_tracker"
--
-- Expect a permission-denied error, NOT a row array and NOT an empty array —
-- an empty array would mean privileges are open and only RLS is holding, which
-- is one mistake away from exposure.
--
-- If you later build edit/delete UI, privileges and policies are separate
-- gates; under Pattern A only the grant is needed:
--
--   grant update, delete on
--       finance_tracker.receipts, finance_tracker.disbursements
--       to service_role;
-- ---------------------------------------------------------------------------
grant update, delete on
      finance_tracker.receipts, finance_tracker.disbursements
      to service_role;
